repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]

      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [python]

      - id: setup-cfg-fmt
        name: setup-cfg-fmt
        entry: setup-cfg-fmt
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]

      - id: prettier
        name: prettier
        entry: prettier --write
        language: system
        types: [javascript, json, css, html, yaml]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        files: \.sh$
